### ISSUE TITLE
Nannou-workshop

### ISSUE THREAD

**Issue by cbrevik** [rust-trondheim/.github#1]
Forslag om å holde en workshop om Nannou. Tentativt 8 februar (eller deromkring)

**Comment by eirikblekesaune** [comment]
Jeg kan gjerne holde en workshop i `nannou`. Skal gjøre en lignende workshop i løpet av Mars. Foreslår derfor å evt. ta den `nannou`-workshop i Mars istedet. Kan det funke for dere?

**Comment by eirikblekesaune** [comment]
Forslag til dato: 15. Mars 2023.

**Comment by cbrevik** [comment]
Ja det funker bra, booker inn tentativt 15. mars allerede

**Comment by cbrevik** [comment]
Der snakket du om at kanskje noen flere skulle være med å holde workshop? Noen jeg burde invitere inn her ellers?

**Comment by eirikblekesaune** [comment]
Da har vi satt dato. Jeg lager et repo for workshopen etterhvert som vi kan go public med på workshop-dagen.
