### ISSUE TITLE
Tauri-presentasjon

### ISSUE THREAD

**Issue by cbrevik** [rust-trondheim/.github#10]

**Comment by cbrevik** [comment]
Preppe assistenter på forhånd

**Comment by cbrevik** [comment]
Denne utgikk kanskje @eirikblekesaune ?

**Comment by eirikblekesaune** [comment]
Thomas som vi snakket med flyttet jo til Sverige, dessverige, så jeg tenker at vi kanskje legger denne på ønskeliste enn så lenge.

**Comment by cbrevik** [comment]
🥁

**Comment by cbrevik** [comment]
Gull
