### ISSUE TITLE
Bevy / spill-programmering

### ISSUE THREAD

**Issue by cbrevik** [rust-trondheim/.github#12]
Potensielt med Geir Sagberg?

**Comment by geirsagberg** [comment]
Heisann, kunne absolutt vært artig :) Hva tror du folk er interessert i å høre om? Getting started, ECS, grafikk og shaders, eller noe annet?

**Comment by eirikblekesaune** [comment]
Superkult at du kan tenke deg å ta en runde med dette. Det er nok mange som kommer til å kicke på dette.

Av erfaring så ser vi at alle som holder disse meetupene kommer seg igjennom  25%-50% av det de hadde på blokka. Avhengig om du legger opp til workshop eller foredrag, så trenger gjerne folk lit tid til å få installert ting, eller det dukker opp spørsmål underveis som kan være gøy og gå inn i.
Jeg tenker kanskje at Getting started med Bevy, og noen konseptuelle tanker rundt ECS kanskje er det mest essentielle kanskje?

**Comment by geirsagberg** [comment]
> Også er jo kult for folk å høre om ting du har gjort med Bevy, så kanskje snakke litt om det spillprosjektet du gjorde som vi snakket litt om i går?

Den er grei, har masse eksempler på uferdige spill å vise :D

> Er det forresten en tid neste halvår som passer bra for deg?

Kalenderen er ganske åpen så langt! Er bortrest 18.-21. januar, men ellers er det bare å foreslå en dato så passer den mest sannsynlig!

**Comment by cbrevik** [comment]
Supert! Vi er ganske fleksibel egentlig på tidspunkt. Har et par ting planlagt for neste år, men dato er ikke skrevet i stein på de andre Meetup-ene. 

For å gi litt tid til prepping kunne vi ev. sagt midten av februar?

**Comment by eirikblekesaune** [comment]
Hei Geir og godt  nyttår til deg? Vi har snakket om midten av Februar for Bevy workshop: Hvordan passer det med 14. Februar evt.?

**Comment by geirsagberg** [comment]
Godt nyttår, ja det burde funke!

**Comment by eirikblekesaune** [comment]
Nå beklager jeg at det blir fram og tilbake her, men vi har fått litt tilbakemelding fra flere som kunne tenkt seg å komme på Rust Meetup, men ikke kan på onsdager. Dette kommer til å bli en skikkelig kul meetup, som mange kommer til å ha lyst til å komme på, så vi har lyst til å få med oss en del folk.
Vi lurte derfor på om du evt kunne tatt det tirsdag den 13. istedet, evt tirsdag den 20. Februar? Hvis det ikke lar seg gjøre så holder vi på onsdag den 14. altså.

**Comment by geirsagberg** [comment]
Tirsdag 13. skal gå fint også!

**Comment by cbrevik** [comment]
Flotters @geirsagberg! Det ble etterspurt om vi kunne legge inn februar-eventen på Meetup i går. Er ikke hastverk, men tror det hadde vært bra om vi lander omfang/beskrivelse jeg kan legge ut. Hvis du vil Geir så kan vi ev. lage en midlertidig kanal på Discord (https://discord.gg/G7Wg4spQ8s) hvor vi kan planlegge og holde kontakten fram til Meetup. Ellers hvis Discord ikke er din greie kan vi fortsette det arbeidet her også altså :D
