### ISSUE TITLE
Meetup med Torleif Sandnes

### ISSUE THREAD

**Issue by eirikblekesaune** [rust-trondheim/.github#13]

**Comment by torleifs** [comment]
I have worked with both threads and InterProcess communication in my last contracting work and have eventually mustered enough courage to talk about this in front of a crowd, so I accept the challenge.

What level is appropriate? 
Do you think the audience will be system developers with previous experience with multi-threaded programming?

I was thinking of having a presentation first, and then move on to let eveybody work on a set of excercises.
Do we have time for this?

**Comment by eirikblekesaune** [comment]
Dette høres veldig bra ut. 😃 
Generelt så varierer jo publikummet litt. Jeg tenker jo egentlig at om du snakker om multi-threading, så vil det sikkert være mange som er ekstra interessert i å ta turen jeg da. Da kan vi jo gjøre en skikkelig jobb med promoteringen, kanskje targete noen miljøer som kan være ekstra interesserte i det kanskje?

Vi kan jo holde så lenge vi vil egentlig, men erfaringsvis er sjeldent folk henger lengre enn et par timer, men om det er ting å holde på med så er jo det positivt.

**Comment by eirikblekesaune** [comment]
Da sikter vi oss inn på 12. Mars

**Comment by torleifs** [comment]
Som vi snakket om i går er det tentative planen noe sånt som:

1. Fork-Join parallellism, gå gjennom spawn(), join(), move semantics og closures
   - Oppgave: parallellisere arbeid på en vektor over de kjernene som er tilgjengelig på din datamaskin
   - Er det mulig å fordele arbeidet bedre over trådene?
2. Scoped threads, forklar litt om Scope, RAII
   - Oppgave: Er det mulig å "låne" en variabel i en tråd og så bruke den etter at trådene er joinet?
3. Kanaler, mpsc
    - Oppgave: Lag en tråd som kan prosessere kommandoer som sendes fra en annen tråd.
    - Oppgave:  Lag flere tråder som sender kommandoer til tråden som kan ta i mot kommandoer
4. Synkroniserings-primitiver, mutex og Condvar.
    - Oppgave: Lag en kanal (Crust of Rust: channels)
    
Mulig at dette blir for mye, så det er sannsynlig at vi hopper over 4.
Jeg tenker å lage et repo der skjelettet til oppgavene er klare, sånn at vi sparer litt tid der.
