### ISSUE TITLE
Show and tell

### ISSUE THREAD

**Issue by sverrejb** [rust-trondheim/.github#14]
Om nok folk committar i forkant hadde det kanskje vore kult med show and tell der folk kan vise fram ting dei har laga i/med Rust. Tippar kanskje 5-10 min kvar.

**Comment by cbrevik** [comment]
Denne synes jeg er gøy også CC @eirikblekesaune @AndersNS 

Artig inngangsvinkel å senke terskelen og gjør potensielt at flere er villig til å dele? Typ "jeg har laget denne lille CLI-toolen for mitt spesifikke problem".

**Comment by sverrejb** [comment]
Eg kan vertfall tenke meg å halde eit innlegg. Kanskje nokon™  kan prøve fiske litt på dei neste meetupsa om fleire vil?

**Comment by rosvik** [comment]
Liker konseptet! Tenker jeg kan vise frem noen greier jeg har laget også: Har et par nettsider/apier som bruker [axum](https://docs.rs/axum) og [image](https://docs.rs/image) blant annet 🦀 (https://github.com/rosvik/img.248.no og/eller https://github.com/rosvik/qr.248.no)

**Comment by eirikblekesaune** [comment]
Da har vi tre stykker som har vist interesse for å vise noe på en show and tell: @sverrejb , @rosvik og en til jeg har snakket med fra Kodeworks. Jeg lager en gruppe på Discord for det, så kan vi planlegge dato og sånn der? Høres det okay ut @sverrejb @rosvik @cbrevik @AndersNS ?

**Comment by eirikblekesaune** [comment]
Da ser det ut som vi sikter oss inn på meetup tirsdag den 23. April. V har to bekreftede show-and-tellere @rosvik  og @junlarsen, og muligens @sverrejb.

**Comment by sverrejb** [comment]
23. April burde gå fint for meg! Beklager sein respons!

**Comment by eirikblekesaune** [comment]
Dette blir gøy! Da trenger vi en eller to setninger fra hver av dere som sier noe i grove trekk hva dere skal vise fram. Det kan være noe så enkelt som: "jeg skal vise fram et program jeg har laget som sorterer tall". Så
Lager vi en vanvittig spennende eventtekst, som gjør at selv ikke den mest Rust-skeptiske programmerer ikke klarer å holde seg unna.

**Comment by rosvik** [comment]
> Skal vise frem hvordan jeg har implementert bildeoptimalisering for et Next.js prosjekt i Rust. Her får man høre historien om hvordan en rust-nybegynner satte opp et API i Axum for å løse et lite (men ekte) frontend-problem, ved hjelp av Rust på serveren!

**Comment by sverrejb** [comment]
Eg skal snakke om infoskjermen eg har laga for kontoret vårt, ein GUI-applikasjon som kjører på ein raspberry pi.

Du må gjerne formulere/spice det opp som du vil ✌️

**Comment by junlarsen** [comment]
Jeg skal snakke kort om hvordan vi i Linjeforeningen Online har hjemmesnekret en Slack bot i Rust for moro skyld
