### ISSUE TITLE
Intro til WebAssembly i rust

### ISSUE THREAD

**Issue by AndersNS** [rust-trondheim/.github#3]
Viser hva jeg har gjort på et hobbyprosjekt. Litt fordeler og ulemper med WebAssembly.

**Comment by eirikblekesaune** [comment]
Er det mulig for eksempel å ta dette den 12. April? 
Er det en presentasjon som du ønsker å bruke en meetup på, eller er det bedre å f.eks. Kombinere det med @cbrevik sin #5 ? Eller skal vi for eksempel ta 12. April til den ene presentasjonen, og den andre f.eks 10. Mai? (Da ligger vi på meetup hver 4. uke)
Det som er fint med én presentasjon er jo at man snakke mer i dybden av det og f.eks. se mer på implementasjondetaljene.
Men om det ikke er noe dere ønsker, så er det jo mulig å kombinere?

**Comment by cbrevik** [comment]
Synes det er en interessant tanke å kombinere 🤔 Usikker om innholdet i #5 er en "hel" meetup verdig enda. Hva tenker du @AndersNS? Jeg ser for meg at wasm er noe som kan fort fylle en hel meetup om en ønsker. 

Sånn sett kan #5 for min del pushes lengre frem i tid om f. eks. det er sjanse for #6. Har en anelse om at embedded Rust og wasm trekker mer publikum enn Azure Functions 😂

**Comment by eirikblekesaune** [comment]
Jeg tror alle tre arrangementene kan bli populære jeg altså. Hva om vi tenker de alle overhengende tematisk?
* 15.02 - **Introduksjon til Rust**: #2 
* 15.02 - **Kreativ koding**: #1 
* 12.04 - **WebAssembly**: Intro til WebAssembly og Cloudflare Workers i rust
* 10.05 - **Embedded**: #6 
* 07.06 - **Rust i skyen**: #5 

Og hvis for eksempel du synes #5 blir litt for snevert, så kan vi evt. bygge på med evt. noen andre som kan presentere noe sky-relatert, evt. kjøre en slags hackaton eller noe? Pluss at vi legger det litt lengre fram, slik at du får bedre tid til å planlegge hva som skal inn?

**Comment by cbrevik** [comment]
Ja, tror jeg trenger den tiden til juni uansett, vet april/mai blir ganske tettpakket med annet konferanse-arbeid for min del ✌ 

Synes listen din er god, så legger inn tenative datoer som felt på sakene i project-boardet her. Så kan vi justere.

**Comment by eirikblekesaune** [comment]
Flott, da kan jeg kontakte Sigvart og høre om han, eller noen de han jobber med, har mulighet den 10.05.

**Comment by eirikblekesaune** [comment]
Sigvart er bortreist den 10.Mai dessverre, men jeg spør om han kan den 12.April hvis det funker for dere?

**Comment by eirikblekesaune** [comment]
Den 12. April funket for Sigvart, så da kjører vi på med Embedded workshop den dagen. Er det okay for dere? Da vil vi kanskje ta WebAssembly den 10.Mai @AndersNS, hvis det passer for deg ?

**Comment by AndersNS** [comment]
10 mai passer sikkert fint

**Comment by AndersNS** [comment]
Kan ta cloudflare workers ved en annen anledning kanskje, så blir dette en rendyrket webassembly-sesjon

**Comment by eirikblekesaune** [comment]
Hei dere, godt nyttår!
Skal vi se om vi får satt en dato for denne meetupen? Hvordan ser tidsskjemaet for Januar og Februar ut for dere?
