### ISSUE TITLE
Intro til embedded Rust med Microbit

### ISSUE THREAD

**Issue by eirikblekesaune** [rust-trondheim/.github#6]
Talk eller workshop om embdedded Rust.
Mulig å få noen av gjengen fra Nordic Semiconductor til å bidra her for eksempel?

**Comment by eirikblekesaune** [comment]
Har meldt med Sigvart som svarer:

> Hei Eirik kan godt prøve å få kjørt en embedded rust intro med microbit. Skal høre litt rundt på kontoret for å få samlet hardware men ganske sikker på at vi har en del microbits:v2 til overs.

**Comment by cbrevik** [comment]
Oi veldig godt initiativ @eirikblekesaune! Har hatt en liten drøm om å prøve meg på embedded Rust, så blir skikkelig gira nå 🤩 Tror ikke jeg er alene der så tror dette kan bli en veldig populær workshop

**Comment by sigvartmh** [comment]
Bare å assigne den til meg 🍡

**Comment by eirikblekesaune** [comment]
Supert @sigvartmh !

**Comment by cbrevik** [comment]
Flott 🤩 det er gjort! Tentativ dato er satt til 10. mai, men det må du gjerne være med å mene noe om @sigvartmh 😊

**Comment by sigvartmh** [comment]
Da har jeg fått tak i 20stk microbits + kabler til workshoppen 👍 Får tak i flere hvis det blir veldig mange som møter opp på workshopen.

**Comment by eirikblekesaune** [comment]
> Da har jeg fått tak i 20stk microbits + kabler til workshoppen 👍 Får tak i flere hvis det blir veldig mange som møter opp på workshopen.

Wow @sigvartmh !! Dette blir en hit altså. Er det nødvendig å lage en antallsbegrensning og påmelding, for å sikre at alle som kommer får mulighet til å jobbe med en? Kan jo fort blir mange hender og føtter?

**Comment by sigvartmh** [comment]
Skulle vi satt denne som upcoming kanskje?

**Comment by eirikblekesaune** [comment]
> Skulle vi satt denne som upcoming kanskje?

Jess! Dette blir steinbra. 🎆 
Har du noen ønsker eller behov for hjelp til gjennomføringen tror du? Det kan jo feks være greit å få satt opp bord strømpadder osv litt forkant eller noe sånt?

**Comment by sigvartmh** [comment]
Bord og strømpadder er sikkert greit. 
Uten om det tror jeg ikke det.

**Comment by cbrevik** [comment]
Jeg (og flere) er nok til stedet on location for å hjelpe til med oppsett. Kunne tenkt meg at vi tar et videomøte litt i forkant av Meetupen og planlegger kjøreplan. Men er jo ei god stund til enda så kan snakkes om det 🤓
